### PR TITLE
Rewrite/rename import_reg management command

### PR DESCRIPTION
**Pull request by cmc333333**
In the process, drop workarounds for Python 2.6 (we support 2.7, 3.4+), remove
unnecessary code, and add tests.

Builds on #64

### CODE REVIEW

**Comment by gregoryfoster** [comment]
Thanks for taking care of this, @cmc333333.  I'd suggest also updating the project's `README.md` to update [usage of the command](https://github.com/eregs/regulations-core#importing-regulation-json).

**Comment by cmc333333** [comment]
@gregoryfoster thanks! I think the latest commit does that, but maybe I missed something?

**Comment by gregoryfoster** [comment]
@cmc333333, my mistake!  I missed that file in a scan of the changed files on the pull request.  Confirmed locally by looking directly at the file.

**Comment by cmc333333** [comment]
Whoot, whoot, thanks for reading it over!

**Pull request merged**
